=== alzmbrini-star/SCORMIFY_Completo/frontend/public/scorm_v2/imscp_rootv1p1p2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
    xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
    elementFormDefault="qualified">
    <xsd:element name="manifest"/>
    <xsd:element name="organizations"/>
    <xsd:element name="organization"/>
    <xsd:element name="item"/>
    <xsd:element name="resources"/>
    <xsd:element name="resource"/>
    <xsd:element name="file"/>
    <xsd:element name="metadata"/>
    <xsd:element name="title" type="xsd:string"/>
    <xsd:element name="schema" type="xsd:string"/>
    <xsd:element name="schemaversion" type="xsd:string"/>
</xsd:schema>

=== alzmbrini-star/SCORMIFY_Completo/backend/static_test/scorm_live/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="SCORM_b16e057c-3465-4428-be6f-12030439aa6e" version="1.0"
    xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
    xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                        http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                        http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
    <metadata>
        <schema>ADL SCORM</schema>
        <schemaversion>1.2</schemaversion>
    </metadata>
    <organizations default="org1">
        <organization identifier="org1">
            <title>Teste de Libras</title>
            <item identifier="item1" identifierref="resource1">
                <title>Teste de Libras</title>
                <adlcp:masteryscore>80</adlcp:masteryscore>
            </item>
        </organization>
    </organizations>
    <resources>
        <resource identifier="resource1" type="webcontent" adlcp:scormtype="sco" href="index.html">
            <file href="index.html"/>
            <file href="course.json"/>
            <file href="scripts/scorm-api.js"/>
            <file href="scripts/quiz-controller.js"/>
            <file href="scripts/player.js"/>
            <file href="scripts/tutor.js"/>
            <file href="styles/tutor.css"/>
            <file href="assets/f96f0247-09a2-4d0d-8391-d33ca6a85506.png"/>
            <file href="assets/59701cbc-85dc-4293-8e9c-a1e232432b09.png"/>
            <file href="assets/55891c08-df36-4d1e-80aa-d16584f1f11e.png"/>
            <file href="assets/ba64e6f8-57f9-4f82-b67e-c93e59934ed5.png"/>
            <file href="assets/ffdd1838-ed70-4d40-a7ba-9b7445f435e3.jpg"/>
            <file href="assets/15548071-db3f-4cdc-b5eb-c61fe4db0e12.jpg"/>
            <file href="assets/3d16a601-662c-4d2e-8b08-90b55f8b94a3.png"/>
            <file href="assets/4fb59014-d495-43c9-8179-ad6f8523cb28.jpg"/>
            <file href="assets/006ff336-0049-4d1d-ab25-dd9928ea32b1.jpg"/>
            <file href="assets/a80b9d93-59b5-4cda-8f72-c42c8314de94.jpg"/>
            <file href="assets/2c0e3315-ed50-4650-8113-5d587a3b7c75.png"/>
            <file href="assets/723c75aa-6bc6-40b1-a536-63e53d8e26f3.jpg"/>
            <file href="assets/cde40c31-128a-40f7-970e-d7265f2b263c.jpg"/>
            <file href="assets/048bd1e5-d4c1-4584-b5c0-a729faef514a.jpg"/>
            <file href="assets/0e787e8e-8427-4391-a30b-f443a1637df7.jpg"/>
            <file href="assets/569c7e20-c75f-4a57-bbe5-0f5ec5443edb.png"/>
            <file href="assets/ce1727d3-7e20-4121-bb66-fc8cc1be900d.jpg"/>
            <file href="assets/9a232602-92a3-43a6-a9ef-0de0ed5a6b8e.jpg"/>
            <file href="assets/dea21ae6-b165-4f17-8237-cdef2d21ba21.jpg"/>
            <file href="assets/62984ec2-6364-45a7-baf2-8c7867a4e2dc.jpg"/>
            <file href="assets/d6e13e3e-dd06-4aa4-acaf-249e3aafdeb4.png"/>
            <file href="assets/841a4ce8-84d8-4691-acac-401e7919769c.png"/>
            <file href="assets/6ff438fc-9a1d-4947-9579-3c164b9968f8.png"/>
            <file href="assets/61b3a788-a69c-456c-b1c6-34a0b294063a.jpg"/>
            <file href="assets/9f7410b7-35db-4cb6-b962-93f087761108.jpg"/>
            <file href="assets/9cb74a07-b372-48ad-b463-6121c7ddaf97.jpg"/>
            <file href="assets/audio_906b5ff6-03a8-4f13-8e1e-526d1e160977.mp3"/>
            <file href="assets/eda15588-52e2-4d6d-a7f8-fef37f21832f.png"/>
            <file href="assets/53fd8708-a653-4ff9-b6e2-41c2edb8f37b.jpg"/>
            <file href="assets/a164da20-7d5c-48ce-80f6-5420496fabdc.png"/>
            <file href="assets/e82f60b5-5627-4a3c-995d-f743c0b3b0c0.png"/>
            <file href="assets/6dd259b6-83d4-40fb-88c3-562457078924.png"/>
            <file href="assets/9640efb5-3094-4b70-8748-e9e65762d442.png"/>
            <file href="assets/audio_33d9ab1b-43b9-4e2f-88e1-f4288bd21ef5.mp3"/>
            <file href="assets/78136a9d-7fa7-4ee6-80ed-0dda5cf40cae.png"/>
            <file href="assets/1bb6ea09-8883-4bcd-ae15-d2a4c6c57457.jpg"/>
            <file href="assets/5d13dde2-4200-43ef-83e9-3fe535b09417.png"/>
            <file href="assets/27d5dbaf-b9fb-48b8-9b24-38b7982fbbdb.jpg"/>
            <file href="assets/23ee1c2c-6cd0-4623-ad9d-5647e0cb084b.jpg"/>
            <file href="assets/d6e16721-128f-49ab-9852-b732fcc1508b.jpg"/>
            <file href="assets/73aa07d2-c201-4fe2-9d68-1efd04d99c3e.png"/>
            <file href="assets/7e53d874-f05a-4629-bee5-9c582b2cc42e.jpg"/>
            <file href="assets/17742f12-4200-46fa-b3ba-d4f58b75bf2f.jpg"/>
            <file href="assets/video_2f729e2c7219.webm"/>
            <file href="assets/64b6f410-131c-4a7c-8a84-5f19f0c206b6.png"/>
            <file href="assets/5fdd533c-160f-4308-8f56-6080436fe6af.png"/>
        </resource>
    </resources>
</manifest>

=== alzmbrini-star/SCORMIFY_Completo/frontend/public/scorm_test/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="SCORM_37d657c7-1f5b-47d5-b36f-92812c5f23dd" version="1.0"
    xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
    xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                        http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                        http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
    <metadata>
        <schema>ADL SCORM</schema>
        <schemaversion>1.2</schemaversion>
    </metadata>
    <organizations default="org1">
        <organization identifier="org1">
            <title>37d657c7-1f5b-47d5-b36f-92812c5f23dd_Teste de conversor PPT</title>
            <item identifier="item1" identifierref="resource1">
                <title>37d657c7-1f5b-47d5-b36f-92812c5f23dd_Teste de conversor PPT</title>
                <adlcp:masteryscore>80</adlcp:masteryscore>
            </item>
        </organization>
    </organizations>
    <resources>
        <resource identifier="resource1" type="webcontent" adlcp:scormtype="sco" href="index.html">
            <file href="index.html"/>
            <file href="course.json"/>
            <file href="scripts/scorm-api.js"/>
            <file href="scripts/player.js"/>
            <file href="assets/slide_001.png"/>
            <file href="assets/slide_003.png"/>
            <file href="assets/audio_f7cd9ff3-5550-417f-849b-61923d4424bc.webm"/>
            <file href="assets/slide_004.png"/>
            <file href="assets/audio_da367f4a-b02f-47f2-956e-5ba96197563f.mp3"/>
            <file href="assets/slide_002.png"/>
            <file href="assets/global_audio_e211f2a6-c5c1-476f-b1f1-4135c6ee2266.mp3"/>
            <file href="assets/audio_ed4c26af-c35d-4aad-b936-98857d48c59c.webm"/>
            <file href="assets/audio_6db05710-3610-4c06-9a3b-9a3ed72bb498.webm"/>
            <file href="assets/6f6c9eae-720a-4771-9179-3432049f2e9b.png"/>
            <file href="assets/audio_8c6b3918-c0c8-4e5b-b036-fe6968b13fb9.webm"/>
        </resource>
    </resources>
</manifest>

=== alzmbrini-star/SCORMIFY_Completo/backend/storage/scorm_preview/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="SCORM_b99cdac3-eaa3-4a5e-b017-8dee93db62d6" version="1.0"
    xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
    xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                        http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                        http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
    <metadata>
        <schema>ADL SCORM</schema>
        <schemaversion>1.2</schemaversion>
    </metadata>
    <organizations default="org1">
        <organization identifier="org1">
            <title>PptxGenJS Presentation</title>
            <item identifier="item1" identifierref="resource1">
                <title>PptxGenJS Presentation</title>
                <adlcp:masteryscore>80</adlcp:masteryscore>
            </item>
        </organization>
    </organizations>
    <resources>
        <resource identifier="resource1" type="webcontent" adlcp:scormtype="sco" href="index.html">
            <file href="index.html"/>
            <file href="course.json"/>
            <file href="scripts/scorm-api.js"/>
            <file href="scripts/player.js"/>
            <file href="assets/slide_011.png"/>
            <file href="assets/slide_001.png"/>
            <file href="assets/slide_003.png"/>
            <file href="assets/slide_005.png"/>
            <file href="assets/slide_010.png"/>
            <file href="assets/slide_004.png"/>
            <file href="assets/global_audio_cff57a0e-782f-4395-ac9d-aa4f4c0bb20a.mp3"/>
            <file href="assets/slide_002.png"/>
            <file href="assets/slide_007.png"/>
            <file href="assets/slide_008.png"/>
            <file href="assets/1536ab69-a04a-4d32-baa9-7e9f3954fc18.png"/>
            <file href="assets/slide_009.png"/>
            <file href="assets/slide_012.png"/>
            <file href="assets/slide_006.png"/>
        </resource>
    </resources>
</manifest>

=== alzmbrini-star/SCORMIFY_Completo/backend/storage/exports/scorm_test/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="SCORM_2aed424b-2453-4d0c-9850-6bc5d3b27d97" version="1.0"
    xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
    xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                        http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                        http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
    <metadata>
        <schema>ADL SCORM</schema>
        <schemaversion>1.2</schemaversion>
    </metadata>
    <organizations default="org1">
        <organization identifier="org1">
            <title>PptxGenJS Presentation</title>
            <item identifier="item1" identifierref="resource1">
                <title>PptxGenJS Presentation</title>
                <adlcp:masteryscore>80</adlcp:masteryscore>
            </item>
        </organization>
    </organizations>
    <resources>
        <resource identifier="resource1" type="webcontent" adlcp:scormtype="sco" href="index.html">
            <file href="index.html"/>
            <file href="course.json"/>
            <file href="scripts/scorm-api.js"/>
            <file href="scripts/quiz-controller.js"/>
            <file href="scripts/player.js"/>
            <file href="assets/slide_011.png"/>
            <file href="assets/video_ca6cfd21a2e9.webm"/>
            <file href="assets/slide_001.png"/>
            <file href="assets/slide_003.png"/>
            <file href="assets/slide_005.png"/>
            <file href="assets/slide_010.png"/>
            <file href="assets/slide_004.png"/>
            <file href="assets/slide_002.png"/>
            <file href="assets/slide_007.png"/>
            <file href="assets/slide_008.png"/>
            <file href="assets/slide_009.png"/>
            <file href="assets/global_audio_3577a6de-5318-4f71-9db7-09e8de7898aa.mp3"/>
            <file href="assets/45c84910-0336-44e3-8f45-0225ca1cdf92.png"/>
            <file href="assets/slide_006.png"/>
            <file href="assets/video_2f729e2c7219.webm"/>
        </resource>
    </resources>
</manifest>

=== alzmbrini-star/SCORMIFY_Completo/backend/static_test/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="SCORM_58753bb1-60a3-4190-8de3-ca51203e8f4d" version="1.0"
    xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
    xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                        http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                        http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
    <metadata>
        <schema>ADL SCORM</schema>
        <schemaversion>1.2</schemaversion>
    </metadata>
    <organizations default="org1">
        <organization identifier="org1">
            <title>Demo SCORMIFY completo</title>
            <item identifier="item1" identifierref="resource1">
                <title>Demo SCORMIFY completo</title>
                <adlcp:masteryscore>80</adlcp:masteryscore>
            </item>
        </organization>
    </organizations>
    <resources>
        <resource identifier="resource1" type="webcontent" adlcp:scormtype="sco" href="index.html">
            <file href="index.html"/>
            <file href="course.json"/>
            <file href="scripts/scorm-api.js"/>
            <file href="scripts/quiz-controller.js"/>
            <file href="scripts/player.js"/>
            <file href="assets/f96f0247-09a2-4d0d-8391-d33ca6a85506.png"/>
            <file href="assets/59701cbc-85dc-4293-8e9c-a1e232432b09.png"/>
            <file href="assets/55891c08-df36-4d1e-80aa-d16584f1f11e.png"/>
            <file href="assets/ba64e6f8-57f9-4f82-b67e-c93e59934ed5.png"/>
            <file href="assets/3d16a601-662c-4d2e-8b08-90b55f8b94a3.png"/>
            <file href="assets/4fb59014-d495-43c9-8179-ad6f8523cb28.jpg"/>
            <file href="assets/006ff336-0049-4d1d-ab25-dd9928ea32b1.jpg"/>
            <file href="assets/a80b9d93-59b5-4cda-8f72-c42c8314de94.jpg"/>
            <file href="assets/2c0e3315-ed50-4650-8113-5d587a3b7c75.png"/>
            <file href="assets/048bd1e5-d4c1-4584-b5c0-a729faef514a.jpg"/>
            <file href="assets/0e787e8e-8427-4391-a30b-f443a1637df7.jpg"/>
            <file href="assets/569c7e20-c75f-4a57-bbe5-0f5ec5443edb.png"/>
            <file href="assets/9a232602-92a3-43a6-a9ef-0de0ed5a6b8e.jpg"/>
            <file href="assets/d6e13e3e-dd06-4aa4-acaf-249e3aafdeb4.png"/>
            <file href="assets/841a4ce8-84d8-4691-acac-401e7919769c.png"/>
            <file href="assets/6ff438fc-9a1d-4947-9579-3c164b9968f8.png"/>
            <file href="assets/9f7410b7-35db-4cb6-b962-93f087761108.jpg"/>
            <file href="assets/9cb74a07-b372-48ad-b463-6121c7ddaf97.jpg"/>
            <file href="assets/eda15588-52e2-4d6d-a7f8-fef37f21832f.png"/>
            <file href="assets/a164da20-7d5c-48ce-80f6-5420496fabdc.png"/>
            <file href="assets/e82f60b5-5627-4a3c-995d-f743c0b3b0c0.png"/>
            <file href="assets/6dd259b6-83d4-40fb-88c3-562457078924.png"/>
            <file href="assets/9640efb5-3094-4b70-8748-e9e65762d442.png"/>
            <file href="assets/78136a9d-7fa7-4ee6-80ed-0dda5cf40cae.png"/>
            <file href="assets/1bb6ea09-8883-4bcd-ae15-d2a4c6c57457.jpg"/>
            <file href="assets/5d13dde2-4200-43ef-83e9-3fe535b09417.png"/>
            <file href="assets/27d5dbaf-b9fb-48b8-9b24-38b7982fbbdb.jpg"/>
            <file href="assets/23ee1c2c-6cd0-4623-ad9d-5647e0cb084b.jpg"/>
            <file href="assets/d6e16721-128f-49ab-9852-b732fcc1508b.jpg"/>
            <file href="assets/73aa07d2-c201-4fe2-9d68-1efd04d99c3e.png"/>
            <file href="assets/audio_d2154dd7-f5a9-4e02-876e-41d63b20f953.mp3"/>
            <file href="assets/64b6f410-131c-4a7c-8a84-5f19f0c206b6.png"/>
            <file href="assets/5fdd533c-160f-4308-8f56-6080436fe6af.png"/>
        </resource>
    </resources>
</manifest>
